### ISSUE TITLE
does not work with iterm2

### ISSUE THREAD

**Issue by njordr** [jmcclare/jm-shell#3]
Hi.

I tried with iTerm2, but it doen't work:

```
MACC02V812PHTD5:~ colapintog$ source ~/.local/lib/bash/
colors.sh        colors_unset.sh  ps1
MACC02V812PHTD5:~ colapintog$ source ~/.local/lib/bash/ps1
colapintog@MACC02V812PHTD5:~$
\e[0mcolapintog@MACC02V812PHTD5:~$
\e[0mcolapintog@MACC02V812PHTD5:~$
\e[0mcolapintog@MACC02V812PHTD5:~$
\e[0mcolapintog@MACC02V812PHTD5:~$
```

Thanks

**Comment by octavianx** [comment]
It is NOT an iterm2 issue.
Jm-shell does not support macOS well ,   there are several pitfalls you have to deal with ,  like : 

>from:               echo -ne "\e[0m"
>to:                 echo -ne "\033[0m"

**Comment by jmcclare** [comment]
@njordr I think @octavianx narrowed down one of the issues you are seeing. There are definitely more though.

I haven’t yet tested jm-shell under Mac OS. I’ll see if I can get it working there when I have time.

**Comment by jaziel-lopez** [comment]
just confirmed what's stated above that there are several pitfalls on mac osx
i just did sed replace of \e to \033 globally; the original error msg I saw was gone but still another pop up,
 looking forward to have some free time to have at look at it.

**Comment by jmcclare** [comment]
The round of updates I just pushed should fix all of the Mac OS  / BSD issues. I tested it in Mac OS 10.12 (Sierra).

Re‐open this or create another issue if you find anything I missed.
