### ISSUE TITLE
Python virtual environment

### ISSUE THREAD

**Issue by georgeuy** [jmcclare/jm-shell#4]
Hi, great job, and can you implements compatibility with python virtual environment? 
ie: in normal shell 
`polio@M71e:~/WebSites/src$ . bin/activate`
`(src) polio@M71e:~/WebSites/src$ which python`
`/home/polio/WebSites/src/bin/python`

Greetings

**Comment by jmcclare** [comment]
I have this implemented. It shows the name of your Python virtual environment in the divider / status line.

Most people probably hate the indicator I chose ('S', for ‘snake’), so I’m going to add an environment variable you can set it with. I tried the unicode snake character, but some terminal emulators (Alacritty) don’t draw double width characters properly.

I’ll leave this open until I add that feature. In the meantime it does show your active virtualenv’s name.

**Comment by jmcclare** [comment]
I just pushed an update that lets you set the Python virtual environment indicator with the `PROMPT_VENV_INDICATOR` variable. It also defaults to ‘V’ now instead of ‘S’.
