### ISSUE TITLE
Can't clone the repository

### ISSUE THREAD

**Issue by Moltkex** [jmcclare/jm-shell#5]
Can't clone the repository. 
```
git clone git@github.com:jmcclare/jm-shell.git ~/.local/lib/jm-shell
Cloning into '/home/moltke/.local/lib/jm-shell'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists

```

**Comment by jmcclare** [comment]
This is an issue with your GitHub public key / SSH setup.

If you haven’t long since fixed this the GitHub help page on this issue should show you what you need to do: https://help.github.com/en/articles/error-permission-denied-publickey
